#pragma once

#ifndef _INTERGEN_GENERATED__tracker_arm_H_
#define _INTERGEN_GENERATED__tracker_arm_H_

//@file Interface file for tracker_arm interface generated by intergen
//See LICENSE file for copyright and license information

//host class: ::app

#include <comm/commexception.h>
#include <comm/intergen/ifc.h>

#include <ot/glm/glm_meta.h>

class app;


namespace ot {

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///OT arm tracker interface
class tracker_arm
    : public intergen_interface
{
public:

    // --- interface methods ---


protected:
    // --- interface events (callbacks from host to client) ---
    // ---       overload these to handle host events       ---

    friend class ::app;

    ///Get arm orientation and position, in the reference coord system (-z forward, +x right, +y up)
    //@param rot return rotation quaternion
    //@param pos optional, relative position
    //@return true if tracker is active
    virtual bool data( quat& rot, float3* pos ){ throw coid::exception("handler not implemented"); }

    ///Get button state
    virtual uint buttons(){ throw coid::exception("handler not implemented"); }

    ///Set current position & orientation as the reference one
    virtual void set_reference() {}

    virtual void force_bind_script_events() {}

public:
    // --- host helpers to check presence of handlers in scripts ---

    virtual bool is_bound_data() { return true; }
    virtual bool is_bound_buttons() { return true; }
    virtual bool is_bound_set_reference() { return true; }

public:
    // --- creators ---

    //@param name plugin name
    static iref<tracker_arm> create( const char* name ) {
        return create<tracker_arm>(0, name);
    }

    template<class T>
    static iref<T> create( T* _subclass_, const char* name );

    // --- internal helpers ---

    virtual ~tracker_arm() {
        if (_cleaner)
            _cleaner(this, 0);
    }

    ///Interface revision hash
    static const int HASHID = 2856641786u;

    ///Interface name (full ns::class string)
    static const coid::tokenhash& IFCNAME() {
        static const coid::tokenhash _name = "ot::tracker_arm"_T;
        return _name;
    }

    int intergen_hash_id() const override final { return HASHID; }

    bool iface_is_derived( int hash ) const override final {
        return hash == HASHID;
    }

    const coid::tokenhash& intergen_interface_name() const override final {
        return IFCNAME();
    }

    static const coid::token& intergen_default_creator_static( backend bck ) {
        static const coid::token _dc(""_T);
        static const coid::token _djs("ot::tracker_arm@wrapper.js"_T);
        static const coid::token _djsc("ot::tracker_arm@wrapper.jsc"_T);
        static const coid::token _dlua("ot::tracker_arm@wrapper.lua"_T);
        static const coid::token _dnone;

        switch(bck) {
        case backend::cxx: return _dc;
        case backend::js:  return _djs;
        case backend::jsc: return _djsc;
        case backend::lua: return _dlua;
        default: return _dnone;
        }
    }

    //@return cached active interface of given host class
    //@note host side helper
    static iref<tracker_arm> intergen_active_interface(::app* host);

    template<enum class backend B>
    static void* intergen_wrapper_cache() {
        static void* _cached_wrapper=0;
        if (!_cached_wrapper) {
            const coid::token& tok = intergen_default_creator_static(B);
            _cached_wrapper = coid::interface_register::get_interface_creator(tok);
        }
        return _cached_wrapper;
    }

    void* intergen_wrapper( backend bck ) const override final {
        switch(bck) {
        case backend::js:  return intergen_wrapper_cache<backend::js>();
        case backend::jsc: return intergen_wrapper_cache<backend::jsc>();
        case backend::lua: return intergen_wrapper_cache<backend::lua>();
        default: return 0;
        }
    }

    backend intergen_backend() const override { return backend::cxx; }

    const coid::token& intergen_default_creator( backend bck ) const override final {
        return intergen_default_creator_static(bck);
    }

    ///Client registrator
    template<class C>
    static int register_client()
    {
        static_assert(std::is_base_of<tracker_arm, C>::value, "not a base class");

        typedef intergen_interface* (*fn_client)();
        fn_client cc = []() -> intergen_interface* { return new C; };

        coid::token type = typeid(C).name();
        type.consume("class ");
        type.consume("struct ");

        coid::charstr tmp = "ot::tracker_arm"_T;
        tmp << "@client-2856641786"_T << '.' << type;

        coid::interface_register::register_interface_creator(tmp, cc);
        return 0;
    }

protected:

    static coid::comm_mutex& share_lock() {
        static coid::comm_mutex _mx(500, false);
        return _mx;
    }

    ///Cleanup routine called from ~tracker_arm()
    static void _cleaner_callback(tracker_arm* m, intergen_interface* ifc) {
        m->assign_safe(ifc, 0);
    }

    bool assign_safe(intergen_interface* client__, iref<tracker_arm>* pout);

    typedef void (*cleanup_fn)(tracker_arm*, intergen_interface*);
    cleanup_fn _cleaner = 0;

    bool set_host(policy_intrusive_base*, intergen_interface*, iref<tracker_arm>* pout);
};

////////////////////////////////////////////////////////////////////////////////
template<class T>
inline iref<T> tracker_arm::create( T* _subclass_, const char* name )
{
    typedef iref<T> (*fn_creator)(tracker_arm*, const char*);

    static fn_creator create = 0;
    static const coid::token ifckey = "ot::tracker_arm.create@2856641786"_T;

    if (!create)
        create = reinterpret_cast<fn_creator>(
            coid::interface_register::get_interface_creator(ifckey));

    if (!create) {
        log_mismatch("create"_T, "ot::tracker_arm.create"_T, "@2856641786"_T);
        return 0;
    }

    return create(_subclass_, name);
}

#pragma warning(push)
#pragma warning(disable : 4191)

#pragma warning(pop)

} //namespace

#endif //_INTERGEN_GENERATED__tracker_arm_H_
